export const GOOGLE_FONTS = [
  "Abril Fatface",
  "Arvo",
  "Bebas Neue",
  "Bitter",
  "Cabin",
  "Cinzel",
  "Cormorant Garamond",
  "Crimson Text",
  "Dancing Script",
  "DM Sans",
  "EB Garamond",
  "Fira Sans",
  "Great Vibes",
  "Inter",
  "Italiana",
  "Josefin Sans",
  "Karla",
  "Lato",
  "Libre Baskerville",
  "Lora",
  "Manrope",
  "Merriweather",
  "Montserrat",
  "Mulish",
  "Noto Sans",
  "Noto Serif",
  "Nunito",
  "Open Sans",
  "Oswald",
  "Playfair Display",
  "Poppins",
  "PT Sans",
  "Quicksand",
  "Raleway",
  "Roboto",
  "Rubik",
  "Source Sans 3",
  "Spectral",
  "Ubuntu",
  "Work Sans"
];

export const TABLER_ICONS = [
  ["ti-home", "Casa"],
  ["ti-star", "Estrela"],
  ["ti-heart", "Coracao"],
  ["ti-check", "Confirmar"],
  ["ti-circle-check", "Confirmado"],
  ["ti-phone", "Telefone"],
  ["ti-mail", "E-mail"],
  ["ti-map-pin", "Localizacao"],
  ["ti-brand-whatsapp", "WhatsApp"],
  ["ti-brand-instagram", "Instagram"],
  ["ti-brand-facebook", "Facebook"],
  ["ti-brand-pinterest", "Pinterest"],
  ["ti-photo", "Imagem"],
  ["ti-video", "Video"],
  ["ti-player-play", "Reproduzir"],
  ["ti-arrow-right", "Seta direita"],
  ["ti-arrow-left", "Seta esquerda"],
  ["ti-chevron-down", "Seta abaixo"],
  ["ti-menu-2", "Menu"],
  ["ti-search", "Busca"],
  ["ti-user", "Pessoa"],
  ["ti-users", "Pessoas"],
  ["ti-award", "Premio"],
  ["ti-truck-delivery", "Entrega"],
  ["ti-file-invoice", "Documento"],
  ["ti-ruler-measure", "Medicao"],
  ["ti-route", "Rota"],
  ["ti-tool", "Ferramenta"],
  ["ti-package", "Pacote"],
  ["ti-discount", "Desconto"],
  ["ti-building-store", "Loja"],
  ["ti-briefcase", "Trabalho"],
  ["ti-palette", "Cores"],
  ["ti-bulb", "Ideia"],
  ["ti-shield-check", "Garantia"],
  ["ti-clock", "Horario"],
  ["ti-calendar", "Calendario"],
  ["ti-quote", "Citacao"],
  ["ti-info-circle", "Informacao"],
  ["ti-alert-circle", "Alerta"],
  ["ti-shopping-cart", "Carrinho"],
  ["ti-tag", "Etiqueta"],
  ["ti-world", "Site"],
  ["ti-send", "Enviar"],
  ["ti-download", "Download"],
  ["ti-upload", "Upload"],
  ["ti-plus", "Mais"],
  ["ti-minus", "Menos"],
  ["ti-x", "Fechar"]
];

export function googleFontsStylesheet(fonts = GOOGLE_FONTS) {
  const families = [...new Set(fonts.filter((font) => GOOGLE_FONTS.includes(font)))];
  const query = families.map((font) => `family=${encodeURIComponent(font)}`).join("&");
  return `https://fonts.googleapis.com/css2?${query}&display=swap`;
}
